#!/bin/sh

mkdir -p /usr/local/bin

ln -s -f /opt/durapps/spark-store/bin/spark-store /usr/local/bin/spark-store
ln -s -f /opt/durapps/spark-store/bin/ssinstall /usr/local/bin/ssinstall

cd /tmp/spark-store-install
wget https://d.store.deepinos.org.cn/dcs-repo.gpg-key.asc
apt-key add dcs-repo.gpg-key.asc

update-icon-caches /usr/share/icons/hicolor || true
update-desktop-database /usr/share/applications || true
xdg-mime default spark-store.desktop x-scheme-handler/spk
update-mime-database /usr/share/mime || true

# /tmp/spark-store-install/feedback.sh
